name: Node.js Package Lint, Test and Publish

on:
  push:
    branches:
      - 'master'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint
      - run: yarn test

  build-and-publish-docs:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn docs
      - run: npx gh-pages -d docs
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}

  # Uncomment if you want to publish to GitHub Package Repository
  #
  # build-and-publish-gpr:
  #   needs: lint-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #       with:
  #         fetch-depth: 1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://npm.pkg.github.com/
  #     - run: yarn
  #     - run: yarn build
  #     - run: yarn semantic-release
  #       env:
  #         NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  #         GH_TOKEN: ${{secrets.GH_TOKEN}}
  #         CI: true

  build-and-publish-npm:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - run: yarn semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
